apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: auth-api
spec:
  ports:
    - name: todo-service
      protocol: TCP
      port: 8081
      targetPort: 8081

  selector:
    service: auth-api
