apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: todos-api
spec:
  selector:
    matchLabels:
      app: microservice-app-example
      service: todos-api
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: todos-api
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
          
        image: localhost:5000/todos-api
        name: todos-api
        livenessProbe:
          httpGet:
            path: /non-existent-path
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /non-existent-path
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8082
      restartPolicy: Always
